import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <header>
          <a href="/">
            <h1>renfoc.us</h1>
          </a>
        </header>
        <main>
          {children}
        </main>
        <nav>
          <a href="/">Home</a> |
          <a href="/posts">All Posts</a>
        </nav>
      </body>
    </html>
  );
}
